name: Build and deploy action
on:
  push:
    branches:
      - 'main'
env:
  name_app: cardealer-app

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: Echo gitHubname and repo
        run: echo ${{ github.repository }}/${{ github.ref_name }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/{{env.name_app}}:${{ github.ref_name }}-version-${{ github.run_id }}
